/*
# Déclic Studio — Initial schema

1. New Tables
- `pricing_tiers`: named price grids (e.g. "Tarif Studio"). `rates` JSON stores
  degressive tiered pricing as { tiers: [{ qty, price }], extra_per_photo }.
  `is_default` marks the default grid.
- `sessions`: a photo session identified by a unique human-readable code
  (e.g. DS-8493), linked to a pricing tier, with a status of
  'pending' | 'active' | 'completed'. Only one session can be 'active' at a time
  (enforced by a partial unique index).
- `photos`: photos belonging to a session, with a filename and a vignette URL.
  `hd_ready` tracks whether the HD file has been uploaded to private storage.
- `orders`: a client order on a session: selected photos (array of photo ids),
  customer email, amount, payment status, delivery status, timestamps.

2. Security
- This is a no-auth app (no sign-in screen). The photographer back-office and
  the public client gallery both use the anon key, so all policies are scoped
  to `TO anon, authenticated` with `USING (true)` because the data is
  intentionally public/shared.
- RLS is enabled on every table.

3. Storage
- `vignettes` public bucket (public read).
- `hd-photos` private bucket (read via signed URLs through the back-office /
  edge function only).

4. Important notes
- `sessions.code` is unique and generated by the app (DS-XXXX format).
- A partial unique index ensures at most one 'active' session.
- `pricing_tiers.is_default` defaults to false; the app enforces a single
  default by clearing other rows before setting one (done client-side).
*/

-- ===== pricing_tiers =====
CREATE TABLE IF NOT EXISTS pricing_tiers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  rates jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE pricing_tiers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_pricing_tiers" ON pricing_tiers;
CREATE POLICY "anon_select_pricing_tiers" ON pricing_tiers FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_pricing_tiers" ON pricing_tiers;
CREATE POLICY "anon_insert_pricing_tiers" ON pricing_tiers FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_pricing_tiers" ON pricing_tiers;
CREATE POLICY "anon_update_pricing_tiers" ON pricing_tiers FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_pricing_tiers" ON pricing_tiers;
CREATE POLICY "anon_delete_pricing_tiers" ON pricing_tiers FOR DELETE
  TO anon, authenticated USING (true);

-- ===== sessions =====
CREATE TABLE IF NOT EXISTS sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  pricing_tier_id uuid REFERENCES pricing_tiers(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('pending','active','completed')),
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS sessions_one_active
  ON sessions (id) WHERE status = 'active';

DROP POLICY IF EXISTS "anon_select_sessions" ON sessions;
CREATE POLICY "anon_select_sessions" ON sessions FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_sessions" ON sessions;
CREATE POLICY "anon_insert_sessions" ON sessions FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_sessions" ON sessions;
CREATE POLICY "anon_update_sessions" ON sessions FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_sessions" ON sessions;
CREATE POLICY "anon_delete_sessions" ON sessions FOR DELETE
  TO anon, authenticated USING (true);

-- ===== photos =====
CREATE TABLE IF NOT EXISTS photos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  filename text NOT NULL,
  vignette_url text,
  hd_ready boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE photos ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS photos_session_id_idx ON photos (session_id);
CREATE INDEX IF NOT EXISTS photos_filename_idx ON photos (filename);

DROP POLICY IF EXISTS "anon_select_photos" ON photos;
CREATE POLICY "anon_select_photos" ON photos FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_photos" ON photos;
CREATE POLICY "anon_insert_photos" ON photos FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_photos" ON photos;
CREATE POLICY "anon_update_photos" ON photos FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_photos" ON photos;
CREATE POLICY "anon_delete_photos" ON photos FOR DELETE
  TO anon, authenticated USING (true);

-- ===== orders =====
CREATE TABLE IF NOT EXISTS orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  customer_email text NOT NULL,
  selected_photos uuid[] NOT NULL DEFAULT '{}'::uuid[],
  amount numeric(10,2) NOT NULL DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'pending'
    CHECK (payment_status IN ('pending','paid')),
  delivery_status text NOT NULL DEFAULT 'awaiting_hd'
    CHECK (delivery_status IN ('awaiting_hd','ready','delivered')),
  created_at timestamptz NOT NULL DEFAULT now(),
  paid_at timestamptz,
  delivered_at timestamptz
);
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS orders_session_id_idx ON orders (session_id);
CREATE INDEX IF NOT EXISTS orders_status_idx ON orders (delivery_status);

DROP POLICY IF EXISTS "anon_select_orders" ON orders;
CREATE POLICY "anon_select_orders" ON orders FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_orders" ON orders;
CREATE POLICY "anon_insert_orders" ON orders FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_orders" ON orders;
CREATE POLICY "anon_update_orders" ON orders FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_orders" ON orders;
CREATE POLICY "anon_delete_orders" ON orders FOR DELETE
  TO anon, authenticated USING (true);

-- ===== Storage buckets =====
INSERT INTO storage.buckets (id, name, public)
VALUES ('vignettes', 'vignettes', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('hd-photos', 'hd-photos', false)
ON CONFLICT (id) DO NOTHING;

-- Vignettes: public read, anyone upload/update/delete (anon-key app)
DROP POLICY IF EXISTS "anon_read_vignettes" ON storage.objects;
CREATE POLICY "anon_read_vignettes" ON storage.objects
  FOR SELECT TO anon, authenticated
  USING (bucket_id = 'vignettes');

DROP POLICY IF EXISTS "anon_insert_vignettes" ON storage.objects;
CREATE POLICY "anon_insert_vignettes" ON storage.objects
  FOR INSERT TO anon, authenticated
  WITH CHECK (bucket_id = 'vignettes');

DROP POLICY IF EXISTS "anon_update_vignettes" ON storage.objects;
CREATE POLICY "anon_update_vignettes" ON storage.objects
  FOR UPDATE TO anon, authenticated
  USING (bucket_id = 'vignettes') WITH CHECK (bucket_id = 'vignettes');

DROP POLICY IF EXISTS "anon_delete_vignettes" ON storage.objects;
CREATE POLICY "anon_delete_vignettes" ON storage.objects
  FOR DELETE TO anon, authenticated
  USING (bucket_id = 'vignettes');

-- HD photos: only authenticated can read; anon/anon can upload (photographer
-- back-office uses anon key). Read is restricted so public clients can't
-- download HDs directly; they get signed URLs from the edge function.
DROP POLICY IF EXISTS "anon_insert_hd_photos" ON storage.objects;
CREATE POLICY "anon_insert_hd_photos" ON storage.objects
  FOR INSERT TO anon, authenticated
  WITH CHECK (bucket_id = 'hd-photos');

DROP POLICY IF EXISTS "anon_update_hd_photos" ON storage.objects;
CREATE POLICY "anon_update_hd_photos" ON storage.objects
  FOR UPDATE TO anon, authenticated
  USING (bucket_id = 'hd-photos') WITH CHECK (bucket_id = 'hd-photos');

DROP POLICY IF EXISTS "anon_delete_hd_photos" ON storage.objects;
CREATE POLICY "anon_delete_hd_photos" ON storage.objects
  FOR DELETE TO anon, authenticated
  USING (bucket_id = 'hd-photos');
